name: card_game
description: A sample web application
dev_dependencies:
  angular: any
  angular_ui: any
  web_components: any
  browser: any
  http_server: any
  route: any
transformers:
- angular
- $dart2js:
    minify: false